import NextTopLoader from 'nextjs-toploader'
import StyledComponentsRegistry from 'lib/registry'

// providers
import RootProvider from 'providers/root'
import ThemeProviders from 'providers/nextThemes'

// fonts
import { Inter } from 'next/font/google'

// types and interfaces
import type { PropsWithChildren } from 'typings/App'
import type { Metadata } from 'next'

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

/* eslint-disable react/no-unknown-property */
export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <StyledComponentsRegistry>
        <body className={inter.variable} cz-shortcut-listen="false">
          <ThemeProviders>
            <RootProvider>
              <NextTopLoader showSpinner={false} />
              {children}
            </RootProvider>
          </ThemeProviders>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
