// components JSX
import Dashboard from 'templates/Dashboard'

// types and interfaces
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app'
}

export default async function PageDashboard() {
  return <Dashboard />
}
